bundle: consistent whitespace

diff --git a/os/bundle-linux b/os/bundle-linux
--- a/os/bundle-linux
+++ b/os/bundle-linux
@@ -3,8 +3,8 @@
 set -o pipefail
 box() { boxes -d ansi -s $(tput cols); }
 failed() {
-    echo -e "\n\033[1;31mRelease build failed.\033[0m"
-    exit 1
+  echo -e "\n\033[1;31mRelease build failed.\033[0m"
+  exit 1
 }
 trap 'failed' ERR
 
